title: Matched Filter interpretation of NNs
email: paul.norridge@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Companion webpage to the book "Mathematics for Machine Learning".
  Copyright 2020 by Marc Peter Deisenroth, A. Aldo Faisal, and Cheng Soon Ong. Published by Cambridge University Press.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: ""
github_username:  pnorridge

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

